version: '3.8'

services:
  backend:
    build: ./backend
    # TODO: Add a container for the backend service
  
  db-admin:
    image: adminer
    # TODO: Add a container for the adminer service

  lab4-db:
    image: postgres
    # TODO: Add a container for the database service

volumes:
  # TODO: Add a volume for the database

networks:
  # TODO: Add networks for the database and adminer services